### ISSUE TITLE
PromptCrafter Example Doesn't Apply the Critique

### ISSUE THREAD

**Issue by maroonblazer** [paralleldrive/sudolang-llm-support#12]
I followed the [example in the PromptCrafter section](https://link.medium.com/TPWNbDNlKDb), copying/pasting the prompt directly into a replit file. However when I run it in ChatGPT 4 it doesn't apply the critique. [Here's the prompt I used.](https://replit.com/@maroonblazer/Rolo#PromptCrafter.sudo)

And here's the output after using the /craft command. Notice that we don't get the 'improved description' like that shown in the example:

*Captured at 85mm at f/1.4 on Kodak Portra 400, Mei stands on a rooftop overlooking the vast cityscape. The golden hour paints the horizon with a warm, amber hue, contrasting the partly cloudy sky's soft blue. Mei's Asian features, in her 30s, are illuminated by a warm golden light from the left, casting gentle shadows that accentuate her contemplative expression. A cool silver light diffuses from behind, outlining her silhouette and making her appear almost ethereal against the backdrop. The gentle wind rustles her hair, adding a touch of movement to the scene. The distant city lights twinkle, their glow muted but persistent, mirroring the soft hum of the city below. The mood is melancholic, reminiscent of a Wong Kar-wai film, with the color grade emphasizing moody blues punctuated by golden highlights. The entire scene feels ephemeral, as if Mei is caught in a fleeting moment of reflection amidst the vastness of the world around her.

Improvement Steps:

Target: Original description.
Critique: The description captures the mood and setting but could benefit from a more detailed portrayal of Mei's emotions and the ambiance.
ApplyCritique: Enhanced the description of Mei's contemplative state and the ambiance of the city below.
The revised description provides a richer, more detailed, and riveting portrayal of the scene, adhering to the PromptCrafter instructions and constraints.*

**Comment by ericelliott** [comment]
LLMs are non-deterministic, and sometimes make mistakes. If that happens, try again. Sometimes you will need to start a new session and try again. This works better in Claude 3.5 Sonnet, currently. I tested PromptCrafter today, and could not reproduce this issue.
