### ISSUE TITLE
Idea: Compatibility Matrix

### ISSUE THREAD

**Issue by nitsanavni** [paralleldrive/sudolang-llm-support#20]
I guess some features work some of the time with some of the LMs.  

Idea: Document a Compatibility Matrix

Can take inpiration from e.g. [MDN Compatibility Tables](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Compatibility_tables).

I imagine one axis to be the LM, and the other a SudoLang feature, syntax, etc.
Cells could be boolean (green / red), or could show a percentage for estimated success frequency.

**Comment by ericelliott** [comment]
Thank you. 🙏

I so far have not conclusively identified any feature of SudoLang that is NOT supported by all tested models. If you have some, please supply them.

**Comment by nitsanavni** [comment]
Could also be a way to extend SudoLang to "harder" constructs (harder for LLMs), that may only be reliable on certain models.

**Comment by nitsanavni** [comment]
Or, could be a way to assess weaker, smaller models - how small can you go until some SudoLang constructs become unusable?

**Comment by ericelliott** [comment]
It might be a good idea to provide an overview of how well various models are suited to complex instruction following and reasoning. Spoiler: GPT-4o is not so great. Claude 3.5 is currently a clear winner (best bang-for-buck). OpenAI o1 is pretty great, but slow and expensive. Llama 3+ 70b+ are great. Google Gemma 2 27b beats GPT-4o 👀, but is a little uncreative.
